_G.Ability_Cost_Table = {}

function check_ability(abilityName)
	local has = false 
	local cost = 0
	local name = ""
	for k,v in pairs(Ability_Cost_Table) do
		if abilityName == k 
			then 
				has = true
				cost = v
				name = k
				break 
		end
	end

	if has == true 
		then
			local DataTable = {}
			DataTable.ability_name = name
			DataTable.price = cost
			return DataTable
	end
end

function check_price(abilityName)
local price = 0
	for k,v in pairs(Ability_Cost_Table) do
		if abilityName == k 
			then 
				price = v
				break 
		end
	end
			if price > 0 
			then
				return price
			else
				return
		end
end

local a = Ability_Cost_Table
local b = 500
--new
a.omni_bless_datadriven = 250
a.omni_incagi_datadriven = 250
a.omni_anaphema_datadriven = 350
a.omni_holylight_datadriven = 1000
a.alastar_punch_stats = b
a.alastar_punch_str = b
a.alastar_punch_agi = b
a.alastar_punch_int = b
a.alastar_change = b
a.alastar_bonus_stats = b
--new
a.antimage_blink = 700
a.phantom_roulette = 400
a.antimage_mana_void = 1000
a.axe_counter_helix = 1000
a.axe_culling_blade = 1000
a.bane_fiends_grip = 1500
a.bloodseeker_bloodrage = 400
a.bloodseeker_thirst = 700
a.bloodseeker_rupture = 1000
a.drow_ranger_marksmanship = 1000
a.earthshaker_enchant_totem = 700
a.earthshaker_aftershock_datadriven = 700
a.earthshaker_echo_slam = 1500
a.juggernaut_omni_slash = 1500
a.kunkka_tidebringer = 650
a.kunkka_ghostship = 1000
a.kunkka_ghostship = 35
a.lina_laguna_blade = 1200
a.lion_finger_of_death = 1200
a.mirana_invis = 1800
a.morphling_replicate = 700
a.nevermore_requiem = 1500
a.phantom_lancer_juxtapose = 2000
a.puck_dream_coil = 1200
a.pudge_dismember = 1100
a.razor_plasma_field = 600
a.razor_eye_of_the_storm = 1100
a.skeleton_king_mortal_strike = 700
a.skeleton_king_reincarnation = 2000
a.death_prophet_exorcism = 2000
a.sven_great_cleave = 475
a.sven_gods_strength = 2000
a.storm_spirit_overload = 1000
a.storm_spirit_ball_lightning = 1800
a.sandking_epicenter = 1000
a.tiny_grow = 1500
a.zuus_thundergods_wrath = 1500
a.slardar_amplify_damage = 1500
a.tidehunter_kraken_shell = 900
a.tidehunter_ravage = 2000
a.vengefulspirit_nether_swap = 1000
a.crystal_maiden_frostbite = 600
a.crystal_maiden_brilliance_aura = 300
a.crystal_maiden_freezing_field = 1500
a.windrunner_focusfire = 1500
a.lich_frost_nova = 1000
a.lich_chain_frost = 1000
a.witch_doctor_death_ward = 1200
a.riki_permanent_invisibility = 2500
a.riki_tricks_of_the_trade = 1000
a.enigma_midnight_pulse = 1000
a.enigma_black_hole = 2500
a.tinker_laser = 1000
a.tinker_rearm_cha = 1500
a.sniper_take_aim = 700
a.sniper_assassinate = 1000
a.necrolyte_reapers_scythe = 1500
a.beastmaster_wild_axes = 600
a.beastmaster_primal_roar = 1500
a.queenofpain_blink = 1000
a.queenofpain_sonic_wave = 1100
a.venomancer_poison_nova = 1000
a.faceless_void_time_lock = 1000
a.faceless_void_chronosphere = 1500
a.pugna_life_drain = 1000
a.phantom_assassin_coup_de_grace = 1800
a.templar_assassin_refraction = 600
a.templar_assassin_psionic_trap = 1000
a.viper_viper_strike = 1000
a.luna_moon_glaive = 1000
a.luna_eclipse = 1000
a.dragon_knight_dragon_blood = 600
a.dazzle_shallow_grave = 600
a.dazzle_weave = 1200
a.rattletrap_hookshot = 1200
a.leshrac_pulse_nova = 1200
a.furion_teleportation = 1000
a.furion_wrath_of_nature = 1000
a.life_stealer_rage = 1000
a.naix_feast_c = 500
a.dark_seer_wall_of_replica = 2000
a.clinkz_searing_arrows = 300
a.clinkz_wind_walk = 600
a.clinkz_death_pact = 1000
a.omniknight_repel = 1000
a.omniknight_guardian_angel = 2000
a.enchantress_untouchable = 700
a.enchantress_enchant = 400
a.enchantress_impetus = 1000
a.huskar_inner_vitality = 600
a.huskar_burning_spear = 400
a.huskar_life_break = 700
a.night_stalker_darkness = 700
a.broodmother_insatiable_hunger = 600
a.bounty_hunter_jinada = 700
a.bounty_hunter_track = 800
a.weaver_geminate_attack = 600
a.weaver_time_lapse = 1200
a.jakiro_macropyre = 1000
a.batrider_sticky_napalm = 1000
a.batrider_flaming_lasso = 1300
a.chen_penitence = 400
a.chen_hand_of_god = 800
a.spectre_spectral_dagger = 700
a.spectre_dispersion = 700
a.spectre_haunt = 1500
a.doom_bringer_doom = 1000
a.ancient_apparition_ice_blast = 1500
a.spirit_breaker_charge_of_darkness = 550
a.spirit_breaker_empowering_haste = 300
a.spirit_breaker_greater_bash = 700
a.spirit_breaker_nether_strike = 1000
a.ursa_overpower = 600
a.ursa_fury_swipes = 700
a.ursa_enrage = 1500
a.gyrocopter_flak_cannon=600
a.gyrocopter_call_down=1000
a.alchemist_acid_spray=600
a.alchemist_goblins_greed=1500
a.alchemist_chemical_rage=1000
a.silencer_glaives_of_wisdom_datadriven=350
a.silencer_global_silence=1000
a.obsidian_destroyer_essence_aura_datadriven=700
a.lycan_shapeshift=1000
a.shadow_demon_shadow_poison=700
a.shadow_demon_demonic_purge=1000
a.chaos_knight_chaos_bolt=600
a.chaos_knight_reality_rift=400
a.chaos_knight_chaos_strike=600
a.chaos_knight_phantasm=1200
a.meepo_geostrike=400
a.treant_natures_guise=400
a.treant_living_armor=400
a.treant_overgrowth=1000
a.undying_decay=650
a.undying_flesh_golem=1000
a.disruptor_kinetic_field=600
a.disruptor_static_storm=1500
a.nyx_assassin_vendetta=1000
a.naga_siren_mirror_image=550
a.naga_siren_song_of_the_siren=1200
a.keeper_of_the_light_illuminate=700
a.keeper_of_the_light_chakra_magic=600
a.wisp_relocate=1000
a.slark_dark_pact=700
a.slark_essence_shift=700
a.slark_shadow_dance=1500
a.medusa_split_shot=600
a.medusa_mana_shield_custom=750
a.medusa_stone_gaze=1000
a.troll_warlord_fervor=1000
a.troll_warlord_battle_trance=1000
a.centaur_double_edge=300
a.centaur_return=500
a.centaur_stampede=1200
a.magnataur_empower=1200
a.magnataur_reverse_polarity=1900
a.shredder_reactive_armor=800
a.shredder_chakram=1000
a.bristleback_quill_spray=600
a.bristleback_bristleback=700
a.bristleback_warpath=1000
a.tusk_walrus_punch=900
a.skywrath_mage_ancient_seal=700
a.skywrath_mage_mystic_flare=1100
a.abaddon_death_coil=450
a.abaddon_aphotic_shield=550
a.abaddon_frostmourne=600
a.abaddon_borrowed_time=1800
a.elder_titan_natural_order_custom=800
a.elder_titan_earth_splitter=1000
a.legion_commander_overwhelming_odds=600
a.legion_commander_press_the_attack=800
a.legion_commander_moment_of_courage_datadriven=500
a.legion_commander_duel=1000
a.ember_spirit_sleight_of_fist=900
a.ember_spirit_flame_guard=700
a.abyssal_underlord_firestorm=1000
a.abyssal_underlord_atrophy_aura=600
a.terrorblade_reflection=600
a.terrorblade_metamorphosis=800
a.terrorblade_sunder=700
a.phoenix_supernova=1000
a.oracle_false_promise=1000
a.mana_break_datadriven =b
a.antimage_spell_shield=b
a.axe_berserkers_call=b
a.axe_battle_hunger=b
a.bane_enfeeble=b
a.bane_brain_sap=b
a.bloodseeker_blood_bath=b
a.drow_ranger_frost_arrows=b
a.drow_ranger_silence=b
a.drow_ranger_wave_of_silence=b
a.drow_ranger_trueshot=b
a.earthshaker_fissure=b
a.juggernaut_blade_dance=b
a.juggernaut_blade_fury=b
a.juggernaut_healing_ward=b
a.kunkka_torrent=b
a.kunkka_x_marks_the_spot=b
a.lina_dragon_slave=b
a.lina_light_strike_array=b
a.lina_fiery_soul_datadriven=500
a.lion_impale=b
a.lion_voodoo=b
a.lion_mana_drain=b
a.mirana_arrow=b
a.mirana_leap=b
a.morphling_waveform=b
a.morphling_adaptive_strike=b
a.nevermore_necromastery=b
a.nevermore_dark_lord=b
a.phantom_lancer_spirit_lance=b
a.phantom_lancer_doppelwalk=b
a.phantom_lancer_phantom_edge=b
a.legion_guardian=b
a.puck_waning_rift=b
a.puck_phase_shift=b
a.pudge_flesh_heap=b
a.pudge_meat_hook=b
a.pudge_rot=b
a.shadow_shaman_ether_shock=b
a.shadow_shaman_voodoo=b
a.shadow_shaman_shackles=b
a.razor_static_link=b
a.razor_unstable_current=b
a.skeleton_king_hellfire_blast=b
a.skeleton_king_vampiric_aura=b
a.death_prophet_carrion_swarm=b
a.death_prophet_silence=b
a.death_prophet_witchcraft=b
a.death_prophet_spirit_siphon=b
a.sven_storm_bolt=b
a.sven_warcry=b
a.storm_spirit_static_remnant=b
a.storm_spirit_electric_vortex=b
a.sandking_burrowstrike=b
a.sandking_sand_storm=b
a.sandking_caustic_finale=b
a.tiny_avalanche=b
a.tiny_toss=b
a.tiny_craggy_exterior=b
a.zuus_arc_lightning=b
a.zuus_lightning_bolt=b
a.zuus_static_field=b
a.slardar_sprint=b
a.slardar_slithereen_crush=b
a.slardar_bash=b
a.tidehunter_gush=b
a.tidehunter_anchor_smash=b
a.vengefulspirit_magic_missile=b
a.vengefulspirit_command_aura=b
a.vengefulspirit_wave_of_terror=b
a.crystal_maiden_crystal_nova=b
a.windrunner_shackleshot=b
a.windrunner_powershot=b
a.windrunner_windrun=b
a.lich_frost_armor=b
a.lich_dark_ritual=b
a.witch_doctor_paralyzing_cask=b
a.witch_doctor_voodoo_restoration=b
a.witch_doctor_maledict=b
a.riki_smoke_screen=b
a.riki_blink_strike=b
a.enigma_malefice=b
a.tinker_heat_seeking_missile=b
a.tinker_march_of_the_machines=b
a.sniper_shrapnel=b
a.sniper_headshot=b
a.necrolyte_death_pulse=b
a.necrolyte_heartstopper_aura=b
a.necrolyte_sadist=b
a.warlock_fatal_bonds=b
a.warlock_shadow_word=b
a.warlock_upheaval=b
a.beastmaster_call_of_the_wild=b
a.beastmaster_call_of_the_wild_boar=b
a.beastmaster_inner_beast=b
a.queenofpain_shadow_strike=b
a.queenofpain_scream_of_pain=b
a.venomancer_venomous_gale=b
a.venomancer_poison_sting=b
a.faceless_void_time_walk=b
a.faceless_void_backtrack=b
a.faceless_void_time_dilation=b
a.pugna_nether_blast=b
a.pugna_decrepify=b
a.pugna_nether_ward=b
a.phantom_assassin_stifling_dagger=b
a.phantom_assassin_phantom_strike=b
a.phantom_assassin_blur=b
a.templar_assassin_meld=b
a.templar_assassin_psi_blades=b
a.viper_poison_attack=b
a.viper_nethertoxin=b
a.viper_corrosive_skin=b
a.luna_lucent_beam=b
a.luna_lunar_blessing=b
a.dragon_knight_breathe_fire=b
a.dragon_knight_dragon_tail=b
a.dazzle_poison_touch=b
a.dazzle_shadow_wave=b
a.rattletrap_battery_assault=b
a.rattletrap_power_cogs=b
a.rattletrap_rocket_flare=b
a.leshrac_split_earth=b
a.leshrac_diabolic_edict=b
a.leshrac_lightning_storm=b
a.furion_sprout=b
a.life_stealer_open_wounds=b
a.dark_seer_vacuum=b
a.dark_seer_ion_shell=b
a.dark_seer_surge=b
a.clinkz_strafe=b
a.omniknight_purification=b
a.omniknight_degen_aura=b
a.enchantress_natures_attendants=b
a.huskar_berserkers_blood=b
a.night_stalker_void=b
a.night_stalker_crippling_fear=b
a.night_stalker_hunter_in_the_night=b
a.broodmother_spin_web=b
a.broodmother_incapacitating_bite=b
a.bounty_hunter_shuriken_toss=b
a.bounty_hunter_wind_walk=b
a.weaver_the_swarm=b
a.weaver_shukuchi=b
a.jakiro_dual_breath=b
a.jakiro_ice_path=b
a.jakiro_liquid_fire=b
a.batrider_flamebreak=b
a.batrider_firefly=b
a.chen_test_of_faith=b
a.chen_hand_of_god=b
a.spectre_desolate=b
a.doom_bringer_scorched_earth=b
a.doom_bringer_infernal_blade=b
a.ancient_apparition_cold_feet=b
a.ancient_apparition_ice_vortex=b
a.ancient_apparition_chilling_touch=b
a.ursa_earthshock=b
a.gyrocopter_rocket_barrage=b
a.gyrocopter_homing_missile=b
a.alchemist_unstable_concoction=b
a.silencer_curse_of_the_silent=b
a.silencer_last_word=b
a.obsidian_destroyer_arcane_orb=b
a.obsidian_destroyer_astral_imprisonment=b
a.obsidian_destroyer_sanity_eclipse=b
a.lycan_howl=b
a.lycan_feral_impulse=b
a.lone_druid_rabid=b
a.lone_druid_savage_roar=b
a.brewmaster_thunder_clap=b
a.brewmaster_drunken_haze=b
a.brewmaster_drunken_brawler=b
a.shadow_demon_disruption=b
a.shadow_demon_soul_catcher=b
a.treant_leech_seed=b
a.ogre_magi_fireblast=b
a.ogre_magi_ignite=b
a.ogre_magi_bloodlust=b
a.undying_soul_rip=b
a.rubick_telekinesis=b
a.rubick_fade_bolt=b
a.rubick_null_field=b
a.disruptor_thunder_strike=b
a.disruptor_glimpse=b
a.nyx_assassin_impale=b
a.nyx_assassin_mana_burn=b
a.nyx_assassin_spiked_carapace=b
a.naga_siren_ensnare=b
a.naga_siren_rip_tide=b
a.keeper_of_the_light_mana_leak=b
a.visage_grave_chill=b
a.visage_soul_assumption=b
a.visage_gravekeepers_cloak=b
a.wisp_tether=b
a.wisp_overcharge=b
a.slark_pounce=b
a.medusa_mystic_snake=b
a.centaur_hoof_stomp=b
a.magnataur_shockwave=b
a.magnataur_skewer=b
a.shredder_whirling_death=b
a.shredder_timber_chain=b
a.bristleback_viscous_nasal_goo=b
a.tusk_ice_shards=b
a.tusk_snowball=b
a.tusk_frozen_sigil=b
a.skywrath_mage_arcane_bolt=b
a.skywrath_mage_concussive_shot=b
a.ember_spirit_searing_chains=b
a.abyssal_underlord_pit_of_malice=b
a.terrorblade_conjure_image=b
a.oracle_fortunes_end=b
a.oracle_fates_edict=b
a.oracle_purifying_flames=b
a.techies_land_mines=b
a.techies_stasis_trap=b
a.techies_suicide=b
a.techies_remote_mines=b
a.winter_wyvern_arctic_burn=b
a.winter_wyvern_splinter_blast=b
a.winter_wyvern_cold_embrace=b
a.winter_wyvern_winters_curse=b

