--========================GLOBALS==================================
_G.RADIANT_HEROES = {}
_G.DIRE_HEROES = {}
_G.DUEL = false
_G.HERO1 = ""
_G.HERO2 = ""
_G.DUEL_TIMER = 0
_G.CORD_RAD = Vector(2390, -2288, 332)
_G.CORD_DIRE = Vector(-2559, 2716, 332)
_G.MMAR = 450 --Max melee attack range
--=========================GLOBALS==========================================

require('internal/util')
require('gamemode')
--require('difficulty_select_UI')
require('spell_shop_UI')
require('system/creeps_spawn')
require('system/duels')
require('system/item_drop')
require('system/item_remove_system')
require('system/filters')
require('system/util')
require('wearables')
require('libraries/IsBoss')
require('libraries/lightning')

--===============================MODIFIERS==============================================
LinkLuaModifier( "modifier_hide_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_cha_invul","libraries/modifiers/modifier_cha_invul.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_cha_invul_duel","libraries/modifiers/modifier_cha_invul.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_creep_grow","libraries/modifiers/modifier_creep_grow.lua", LUA_MODIFIER_MOTION_NONE )
--================================MODIFIERS END=======================================================

function Precache( context )
  DebugPrint("[BAREBONES] Performing pre-load precache")
PrecacheUnitByNameSync("npc_base", context)
PrecacheUnitByNameSync("npc_slark_creep_e", context)
PrecacheUnitByNameSync("npc_slark_creep_m", context)
PrecacheUnitByNameSync("npc_slark_creep_h", context)
PrecacheUnitByNameSync("npc_slark_creep_vh", context)
PrecacheUnitByNameSync("npc_slark_creep_mb", context)
PrecacheUnitByNameSync("npc_doom_creep_e", context)
PrecacheUnitByNameSync("npc_doom_creep_m", context)
PrecacheUnitByNameSync("npc_doom_creep_h", context)
PrecacheUnitByNameSync("npc_doom_creep_vh", context)
PrecacheUnitByNameSync("npc_doom_creep_mb", context)
--=========================PARTICLES===================================== 
PrecacheResource( "particle", "particles/woodchopper_king_black_mantle.vpcf", context )
PrecacheResource( "particle", "particles/woodchopper_king_chop_blood.vpcf", context )
PrecacheResource( "particle", "particles/woodchopper_king_blood_meer.vpcf", context )
PrecacheResource( "particle", "particles/grand_magus_core.vpcf", context )
PrecacheResource( "particle", "particles/grand_magus_core_b.vpcf", context )
PrecacheResource( "particle", "particles/monkey_king_quad_tap_overhead_custom.vpcf", context )
PrecacheResource( "particle", "particles/elder_titan_soul_twice_strength.vpcf", context )
PrecacheResource( "particle", "particles/elder_titan_soul_twice_link.vpcf", context )
PrecacheResource( "particle", "particles/elder_titan_soul_twice_light.vpcf", context )
PrecacheResource( "particle", "particles/items2_fx/manta_phase.vpcf", context )
PrecacheResource( "particle", "particles/items_fx/dust_of_appearance_debuff.vpcf", context )
PrecacheResource( "particle", "particles/items_fx/dust_of_appearance.vpcf", context )
PrecacheResource( "particle", "particles/durandal_s.vpcf", context )
PrecacheResource( "particle", "particles/durandal_c.vpcf", context )
PrecacheResource( "particle", "particles/durandal_d.vpcf", context )
PrecacheResource( "particle", "particles/durandal_miss.vpcf", context )
PrecacheResource( "particle", "particles/durandal_spell.vpcf", context )
PrecacheResource( "particle", "particles/durandal_aura.vpcf", context )
PrecacheResource( "particle", "particles/generic_hero_status/status_invisibility_start_ground.vpcf", context )
PrecacheResource( "particle", "particles/scarlet_edge.vpcf", context )
PrecacheResource( "particle", "particles/generic_gameplay/generic_disarm.vpcf", context )
PrecacheResource( "particle", "particles/static_custom.vpcf", context )
PrecacheResource( "particle", "particles/items_fx/diffusal_slow.vpcf", context )
PrecacheResource( "particle", "particles/items_fx/diffusal_purge_d.vpcf", context )
PrecacheResource( "particle", "particles/armlet_custom.vpcf", context )
PrecacheResource( "particle", "particles/courier_flopjaw_ambient_coins_gold_custom.vpcf", context )
PrecacheResource( "particle", "particles/mana_burn_burn.vpcf", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_abaddon", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_alchemist", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_ancient_apparition", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_antimage", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_arc_warden", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_axe", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_bane", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_batrider", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_beastmaster", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_bloodseeker", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_bounty_hunter", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_brewmaster", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_bristleback", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_centaur", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_chaos_knight", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_chen", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_clinkz", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_crystalmaiden", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_dark_seer", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_dazzle", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_death_prophet", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_disruptor", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_doom_bringer", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_dragon_knight", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_earthshaker", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_elder_titan", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_ember_spirit", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_enchantress", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_enigma", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_faceless_void", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_furion", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_gyrocopter", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_huskar", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_invoker", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_jakiro", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_juggernaut", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_keeper_of_the_light", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_kunkka", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_legion_commander", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_leshrac", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_lich", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_lifestealer", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_abaddon", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_lina", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_lion", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_lone_druid", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_luna", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_lycan", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_magnataur", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_medusa", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_meepo", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_mirana", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_morphling", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_necrolyte", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_nevermore", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_night_stalker", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_nyx_assassin", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_obsidian_destroyer", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_ogre_magi", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_omniknight", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_oracle", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_phantom_assassin", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_phantom_lancer", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_phoenix", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_puck", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_pudge", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_pugna", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_queenofpain", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_rattletrap", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_razor", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_riki", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_rhasta", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_rubick", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_sandking", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_shadow_demon", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_shadowshaman", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_shredder", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_silencer", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_siren", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_skeletonking", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_skywrath_mage", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_slardar", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_slark", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_sniper", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_spectre", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_spirit_breaker", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_stormspirit", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_sven", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_techies", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_templar_assassin", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_terrorblade", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_tidehunter", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_tinker", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_tiny", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_treant", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_troll_warlord", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_tusk", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_undying", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_ursa", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_vengeful", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_venomancer", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_viper", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_visage", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_warlock", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_weaver", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_windrunner", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_winter_wyvern", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_wisp", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_witchdoctor", context )
PrecacheResource( "particle_folder", "particles/units/heroes/hero_zuus", context )
PrecacheResource( "particle_folder", "particles/units/heroes/heroes_underlord", context )
--==========================MODELS=======================================

--=========================SOUNDS======================================
  PrecacheResource("soundfile", "particles/safa_bitch.vpcf", context )
  PrecacheResource("soundfile", "sounds/weapons/creep/neutral/satyr_trickster_purge.vsnd", context )
  PrecacheResource("soundfile", "soundevents/game_sounds_items.vsndevts", context )
  PrecacheResource("soundfile", "soundevents/CustomSounds.vsndevts", context )
  PrecacheResource("soundfile", "soundevents/game_sounds_ui.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_abyssal_underlord.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_alchemist.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_ancient_apparition.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_antimage.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_arc_warden.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_axe.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_bane.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_batrider.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_beastmaster.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_bloodseeker.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_bounty_hunter.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_brewmaster.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_bristleback.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_broodmother.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_centaur.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_chaos_knight.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_chen.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_clinkz.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_crystalmaiden.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_dark_seer.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_dazzle.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_death_prophet.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_disruptor.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_doom_bringer.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_dragon_knight.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_drowranger.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_earthshaker.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_elder_titan.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_enchantress.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_enigma.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_faceless_void.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_furion.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_gyrocopter.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_huskar.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_jakiro.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_juggernaut.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_keeper_of_the_light.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_kunkka.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_legion_commander.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_leshrac.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_lich.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_life_stealer.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_lina.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_lion.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_lone_druid.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_luna.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_lycan.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_magnataur.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_medusa.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_meepo.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_morphling.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_naga_siren.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_nevermore.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_night_stalker.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_nyx_assassin.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_obsidian_destroyer.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_omniknight.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_oracle.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_phantom_assassin.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_phoenix.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_puck.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_pudge.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_pugna.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_queenofpain.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_rattletrap.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_razor.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_riki.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_rubick.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_sandking.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_shadow_demon.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_shadowshaman.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_shredder.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_silencer.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_skeletonking.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_skywrath_mage.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_slardar.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_slark.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_spectre.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_spirit_breaker.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_storm_spirit.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_sven.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_techies.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_templar_assassin.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_terrorblade.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_tidehunter.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_tinker.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_tiny.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_treant.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_troll_warlord.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_tusk.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_undying.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_ursa.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_vengefulspirit.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_viper.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_visage.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_warlock.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_weaver.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_winter_wyvern.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_wips.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_witchdoctor.vsndevts", context)
  PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_zuus.vsndevts", context)
--=========================UNITS=====================================
end

-- Create the game mode when we activate
function Activate()
  GameRules.GameMode = GameMode()
  GameRules.GameMode:InitGameMode()
end